databases:
  - name: fruits
    databaseName: fruits
    user: fruits

services:
  - type: web
    name: fruits
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fruits
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false